version: "3"

services:

    db:
        image: mariadb:10.2
        restart: on-failure
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: shop
            MYSQL_USER: admin
            MYSQL_PASSWORD: 12345
        ports:
            - 3306:3306

    app:
        build: app/
        environment:
            SQLALCHEMY_DATABASE_URI: "mysql://admin:12345@db/shop"
            FLASK_APP: run.py
        ports:
            - 5000:5000
        depends_on:
            - db
        links:
            - db
