version: "3"

services:

    db:
        image: mariadb:10.2
        restart: on-failure
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: shop
            MYSQL_USER: admin
            MYSQL_PASSWORD: 12345
        ports:
            - 3306:3306

    auth:
        build: auth/
        environment:
            SQLALCHEMY_DATABASE_URI: "mysql://admin:12345@db/shop"
            FLASK_APP: run.py
            CONTOUR: production
            MSG_QUEUE: msg_queue
        ports:
            - 5001:5001
        depends_on:
            - db

    notifications:
        build: notifications/
        environment:
            FLASK_APP: run.py
            CONTOUR: production
            MSG_QUEUE: msg_queue
            SMTP_URL: fakesmtp

    app:
        build: app/
        environment:
            SQLALCHEMY_DATABASE_URI: "mysql://admin:12345@db/shop"
            AUTH_URI: auth
            FLASK_APP: run.py
            CONTOUR: production
        links:
            - auth
        ports:
            - 5000:5000
        depends_on:
            - db
            - auth

    msg_queue:
        image: rabbitmq:3-management


    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "1025:25"

        volumes:
            - ./email:/var/mail
